/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.26                          *
*        Compiled Aug 18 2014, 17:12:05                              *
*        (c) 2014 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
#include "main.h"
// USER END

#include "DIALOG.h"

/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_TEXT_0  (GUI_ID_USER + 0x01)
#define ID_EDIT_0  (GUI_ID_USER + 0x02)
#define ID_BUTTON_0  (GUI_ID_USER + 0x03)
#define ID_BUTTON_1  (GUI_ID_USER + 0x04)
#define ID_SLIDER_0  (GUI_ID_USER + 0x05)
#define ID_RADIO_0  (GUI_ID_USER + 0x06)
#define ID_TEXT_1  (GUI_ID_USER + 0x07)
#define ID_TEXT_2  (GUI_ID_USER + 0x08)
#define ID_BUTTON_2  (GUI_ID_USER + 0x09)
#define ID_BUTTON_3  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_4  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_5  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_6  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_7  (GUI_ID_USER + 0x0E)
#define ID_BUTTON_8  (GUI_ID_USER + 0x0F)
#define ID_TEXT_3  (GUI_ID_USER + 0x10)
#define ID_TEXT_4  (GUI_ID_USER + 0x11)
#define ID_BUTTON_9  (GUI_ID_USER + 0x12)
#define ID_BUTTON_10  (GUI_ID_USER + 0x13)
#define ID_TEXT_5  (GUI_ID_USER + 0x14)


// USER START (Optionally insert additional defines)
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
static int first = 1;
static float oldvol;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "SDR_MainForm", ID_WINDOW_0, 1, 0, 320, 240, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Head", ID_TEXT_0, 0, 0, 320, 21, 0, 0x64, 0 },
  { EDIT_CreateIndirect, "Station", ID_EDIT_0, 5, 130, 216, 37, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Fplus", ID_BUTTON_0, 76, 48, 35, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fminus", ID_BUTTON_1, 76, 76, 35, 25, 0, 0x0, 0 },
  { SLIDER_CreateIndirect, "Volume", ID_SLIDER_0, 5, 185, 216, 35, 0, 0x0, 0 },
  { RADIO_CreateIndirect, "Radio", ID_RADIO_0, 5, 25, 67, 98, 0, 0x1405, 0 },
  { TEXT_CreateIndirect, "Volume", ID_TEXT_1, 72, 215, 92, 27, 0, 0x64, 0 },
  { TEXT_CreateIndirect, "LStation", ID_TEXT_2, 40, 108, 165, 25, 0, 0x64, 0 },
  { BUTTON_CreateIndirect, "Mute", ID_BUTTON_2, 224, 215, 70, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "AM", ID_BUTTON_3, 258, 105, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "LSB", ID_BUTTON_4, 258, 130, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "USB", ID_BUTTON_5, 258, 155, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "CW", ID_BUTTON_6, 258, 180, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Narrow", ID_BUTTON_7, 193, 35, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Wide", ID_BUTTON_8, 258, 35, 60, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "BW", ID_TEXT_3, 152, 40, 32, 20, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "AGC", ID_TEXT_4, 152, 65, 35, 17, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Fast", ID_BUTTON_9, 193, 62, 60, 25, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "Slow", ID_BUTTON_10, 258, 62, 60, 25, 0, 0x0, 0 },
  { TEXT_CreateIndirect, "Freq", ID_TEXT_5, 82, 165, 138, 26, 0, 0x64, 0 },
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg) {
  WM_HWIN hItem;
  int     NCode;
  int     Id;
  // USER START (Optionally insert additional variables)
  // USER END

  switch (pMsg->MsgId) {
  case WM_INIT_DIALOG:
    //
    // Initialization of 'SDR_MainForm'
    //
    hItem = pMsg->hWin;
    WINDOW_SetBkColor(hItem, 0x00000000);
    //
    // Initialization of 'Head'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
    TEXT_SetFont(hItem, GUI_FONT_20B_ASCII);
    TEXT_SetText(hItem, "  ARM_RADIO          by Alberto I2PHD");
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Station'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_0);
    EDIT_SetText(hItem, "F=123,456,780.7");
    EDIT_SetTextColor(hItem, EDIT_CI_ENABLED, 0x0000FF40);
    EDIT_SetFont(hItem, GUI_FONT_32B_ASCII);
    EDIT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Fplus'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    BUTTON_SetText(hItem, "+");
    //
    // Initialization of 'Fminus'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
    BUTTON_SetText(hItem, "-");
    BUTTON_SetFont(hItem, GUI_FONT_24B_ASCII);
    //
    // Initialization of 'Radio'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_RADIO_0);
    RADIO_SetTextColor(hItem, 0x0080FFFF);
    RADIO_SetText(hItem, "100s kHz", 0);
    RADIO_SetText(hItem, "10s kHz", 1);
    RADIO_SetText(hItem, "kHz", 2);
    RADIO_SetText(hItem, "100s Hz", 3);
    RADIO_SetText(hItem, "10s Hz", 4);
    //
    // Initialization of 'Volume'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "Volume");
    TEXT_SetTextColor(hItem, 0x00FFFF80);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'LStation'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetText(hItem, "Station");
    TEXT_SetTextColor(hItem, 0x00FFFF80);
    TEXT_SetTextAlign(hItem, GUI_TA_HCENTER | GUI_TA_VCENTER);
    //
    // Initialization of 'Mute'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'AM'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'LSB'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'USB'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_5);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'CW'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_6);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Narrow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_7);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Wide'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_8);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'BW'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'AGC'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Fast'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_9);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Slow'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_10);
    BUTTON_SetFont(hItem, GUI_FONT_16B_ASCII);
    //
    // Initialization of 'Freq'
    //
    hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
    TEXT_SetFont(hItem, GUI_FONT_24B_ASCII);
    TEXT_SetTextAlign(hItem, GUI_TA_RIGHT | GUI_TA_VCENTER);
    TEXT_SetTextColor(hItem, 0x0000FFFF);
    TEXT_SetText(hItem, "12345678 Hz");
    // USER START (Optionally insert additional code for further widget initialization)
      hItem = WM_GetDialogItem(pMsg->hWin, hSTATION);
      EDIT_SetBkColor(hItem, EDIT_CI_ENABLED, GUI_BLACK);
			EDIT_SetFocussable(hItem, false);
			
			hItem = WM_GetDialogItem(pMsg->hWin, hVOL);
			SLIDER_SetRange(hItem, 0, 100);
//--------------------- Initializations -----------------------------------			
			if(first)
			{
        first = false;
        GlobalMsgPtr = pMsg;
			  hItem = WM_GetDialogItem(pMsg->hWin, hVOL);
			  SLIDER_SetValue(hItem, 25);   // initial default volume level
			}	
//--------------------------------------------------------------------------
			Fstep = 100000;
		// USER END
    break;
  case WM_NOTIFY_PARENT:
    Id    = WM_GetId(pMsg->hWinSrc);
    NCode = pMsg->Data.v;
    switch(Id) {
    case ID_EDIT_0: // Notifications sent by 'Station'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_0: // Notifications sent by 'Fplus'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           FplusClicked();
   			// USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_1: // Notifications sent by 'Fminus'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           FminusClicked();
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_SLIDER_0: // Notifications sent by 'Volume'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  hItem = WM_GetDialogItem(pMsg->hWin, hVOL);
        if(!Muted)
			    volume = SLIDER_GetValue(hItem)/100.f;
        else
			    oldvol = SLIDER_GetValue(hItem)/100.f;
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_RADIO_0: // Notifications sent by 'Radio'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      case WM_NOTIFICATION_VALUE_CHANGED:
        // USER START (Optionally insert code for reacting on notification message)
			  hItem = WM_GetDialogItem(pMsg->hWin, hFRADIO);
        SetFstep(RADIO_GetValue(hItem));
			  // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_2: // Notifications sent by 'Mute'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(bouncing()) break;
			     if(Muted)
					 {
             volume = oldvol;
             Muted = false;
						 ChangeColor(pMsg->hWin, hMUTE, GUI_BLACK);
			     }
					 else
					 { 
						 oldvol = volume;	 
						 volume = 0.f;
						 Muted = true;
						 ChangeColor(pMsg->hWin, hMUTE, GUI_RED);
					 }	 
			  // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_3: // Notifications sent by 'AM'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetMode(pMsg->hWin, AM);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_4: // Notifications sent by 'LSB'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetMode(pMsg->hWin, LSB);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_5: // Notifications sent by 'USB'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetMode(pMsg->hWin, USB);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_6: // Notifications sent by 'CW'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetMode(pMsg->hWin, CW);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_7: // Notifications sent by 'Narrow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetBW(pMsg->hWin, Narrow);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_8: // Notifications sent by 'Wide'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetBW(pMsg->hWin, Wide);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_9: // Notifications sent by 'Fast'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetAGC(pMsg->hWin, Fast);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    case ID_BUTTON_10: // Notifications sent by 'Slow'
      switch(NCode) {
      case WM_NOTIFICATION_CLICKED:
        // USER START (Optionally insert code for reacting on notification message)
           if(!bouncing()) SetAGC(pMsg->hWin, Slow);
        // USER END
        break;
      case WM_NOTIFICATION_RELEASED:
        // USER START (Optionally insert code for reacting on notification message)
        // USER END
        break;
      // USER START (Optionally insert additional code for further notification handling)
      // USER END
      }
      break;
    // USER START (Optionally insert additional code for further Ids)
    // USER END
    }
    break;
  // USER START (Optionally insert additional message handling)
  // USER END
  default:
    WM_DefaultProc(pMsg);
    break;
  }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateSDR_MainForm
*/
WM_HWIN CreateSDR_MainForm(void);
WM_HWIN CreateSDR_MainForm(void) {
  WM_HWIN hWin;

  hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
  return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/
